/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export declare namespace TicketMarket {
  export type MarketEventStruct = {
    eventId: BigNumberish;
    uri: string;
    startDate: BigNumberish;
    ticketTotal: BigNumberish;
    ticketsSold: BigNumberish;
    owner: string;
  };

  export type MarketEventStructOutput = [
    BigNumber,
    string,
    BigNumber,
    BigNumber,
    BigNumber,
    string
  ] & {
    eventId: BigNumber;
    uri: string;
    startDate: BigNumber;
    ticketTotal: BigNumber;
    ticketsSold: BigNumber;
    owner: string;
  };

  export type MarketTicketStruct = {
    tokenId: BigNumberish;
    eventId: BigNumberish;
    price: BigNumberish;
    purchaseLimit: BigNumberish;
    totalSupply: BigNumberish;
    royaltyFee: BigNumberish;
    maxResalePrice: BigNumberish;
  };

  export type MarketTicketStructOutput = [
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber
  ] & {
    tokenId: BigNumber;
    eventId: BigNumber;
    price: BigNumber;
    purchaseLimit: BigNumber;
    totalSupply: BigNumber;
    royaltyFee: BigNumber;
    maxResalePrice: BigNumber;
  };

  export type ResaleTicketStruct = {
    resaleId: BigNumberish;
    tokenId: BigNumberish;
    seller: string;
    resalePrice: BigNumberish;
    sold: boolean;
  };

  export type ResaleTicketStructOutput = [
    BigNumber,
    BigNumber,
    string,
    BigNumber,
    boolean
  ] & {
    resaleId: BigNumber;
    tokenId: BigNumber;
    seller: string;
    resalePrice: BigNumber;
    sold: boolean;
  };
}

export interface TicketMarketInterface extends utils.Interface {
  contractName: "TicketMarket";
  functions: {
    "addMoreTicketsToMarket(address,uint256,uint256)": FunctionFragment;
    "buyResaleTicket(address,uint256)": FunctionFragment;
    "buyTicket(address,uint256,uint256)": FunctionFragment;
    "createEvent(string,uint64)": FunctionFragment;
    "createMarketTicket(uint256,uint256,address,uint256,uint256,uint256,uint256,uint256)": FunctionFragment;
    "getAllEvents()": FunctionFragment;
    "getEvent(uint256)": FunctionFragment;
    "getEventTickets(uint256)": FunctionFragment;
    "getMyEvents()": FunctionFragment;
    "getMyResaleListings()": FunctionFragment;
    "getMyTickets(address)": FunctionFragment;
    "getResaleTickets(uint256)": FunctionFragment;
    "listOnResale(address,uint256,uint256)": FunctionFragment;
    "onERC1155BatchReceived(address,address,uint256[],uint256[],bytes)": FunctionFragment;
    "onERC1155Received(address,address,uint256,uint256,bytes)": FunctionFragment;
    "supportsInterface(bytes4)": FunctionFragment;
    "validateTicket(address,address,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "addMoreTicketsToMarket",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "buyResaleTicket",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "buyTicket",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createEvent",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createMarketTicket",
    values: [
      BigNumberish,
      BigNumberish,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllEvents",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEvent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEventTickets",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMyEvents",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMyResaleListings",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMyTickets",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getResaleTickets",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "listOnResale",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "onERC1155BatchReceived",
    values: [string, string, BigNumberish[], BigNumberish[], BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "onERC1155Received",
    values: [string, string, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "validateTicket",
    values: [string, string, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "addMoreTicketsToMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "buyResaleTicket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "buyTicket", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createEvent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createMarketTicket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllEvents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getEvent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getEventTickets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMyEvents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMyResaleListings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMyTickets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getResaleTickets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "listOnResale",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onERC1155BatchReceived",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onERC1155Received",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateTicket",
    data: BytesLike
  ): Result;

  events: {
    "MarketEventCreated(uint256,string,uint64,uint256,uint256,address)": EventFragment;
    "MarketTicketCreated(uint256,uint256,uint256,uint256,uint256,uint256,uint256)": EventFragment;
    "ResaleTicketCreated(uint256,uint256,address,uint256,bool)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "MarketEventCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "MarketTicketCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ResaleTicketCreated"): EventFragment;
}

export type MarketEventCreatedEvent = TypedEvent<
  [BigNumber, string, BigNumber, BigNumber, BigNumber, string],
  {
    eventId: BigNumber;
    uri: string;
    startDate: BigNumber;
    ticketTotal: BigNumber;
    ticketsSold: BigNumber;
    owner: string;
  }
>;

export type MarketEventCreatedEventFilter =
  TypedEventFilter<MarketEventCreatedEvent>;

export type MarketTicketCreatedEvent = TypedEvent<
  [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber, BigNumber, BigNumber],
  {
    tokenId: BigNumber;
    eventId: BigNumber;
    price: BigNumber;
    purchaseLimit: BigNumber;
    totalSupply: BigNumber;
    royaltyFee: BigNumber;
    maxResalePrice: BigNumber;
  }
>;

export type MarketTicketCreatedEventFilter =
  TypedEventFilter<MarketTicketCreatedEvent>;

export type ResaleTicketCreatedEvent = TypedEvent<
  [BigNumber, BigNumber, string, BigNumber, boolean],
  {
    resaleId: BigNumber;
    tokenId: BigNumber;
    seller: string;
    resalePrice: BigNumber;
    sold: boolean;
  }
>;

export type ResaleTicketCreatedEventFilter =
  TypedEventFilter<ResaleTicketCreatedEvent>;

export interface TicketMarket extends BaseContract {
  contractName: "TicketMarket";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: TicketMarketInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addMoreTicketsToMarket(
      nftContract: string,
      tokenId: BigNumberish,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    buyResaleTicket(
      nftContract: string,
      _resaleId: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    buyTicket(
      nftContract: string,
      tokenId: BigNumberish,
      amount: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    createEvent(
      uri: string,
      startDate: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    createMarketTicket(
      eventId: BigNumberish,
      tokenId: BigNumberish,
      nftContract: string,
      purchaseLimit: BigNumberish,
      totalSupply: BigNumberish,
      price: BigNumberish,
      royaltyFee: BigNumberish,
      maxResalePrice: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getAllEvents(
      overrides?: CallOverrides
    ): Promise<[TicketMarket.MarketEventStructOutput[]]>;

    getEvent(
      _eventId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[TicketMarket.MarketEventStructOutput]>;

    getEventTickets(
      _eventId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[TicketMarket.MarketTicketStructOutput[]]>;

    getMyEvents(
      overrides?: CallOverrides
    ): Promise<[TicketMarket.MarketEventStructOutput[]]>;

    getMyResaleListings(
      overrides?: CallOverrides
    ): Promise<[TicketMarket.ResaleTicketStructOutput[]]>;

    getMyTickets(
      nftContract: string,
      overrides?: CallOverrides
    ): Promise<[TicketMarket.MarketTicketStructOutput[]]>;

    getResaleTickets(
      _tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[TicketMarket.ResaleTicketStructOutput[]]>;

    listOnResale(
      nftContract: string,
      _tokenId: BigNumberish,
      price: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    onERC1155BatchReceived(
      arg0: string,
      arg1: string,
      arg2: BigNumberish[],
      arg3: BigNumberish[],
      arg4: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    onERC1155Received(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      arg3: BigNumberish,
      arg4: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    validateTicket(
      nftContract: string,
      userAddress: string,
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  addMoreTicketsToMarket(
    nftContract: string,
    tokenId: BigNumberish,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  buyResaleTicket(
    nftContract: string,
    _resaleId: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  buyTicket(
    nftContract: string,
    tokenId: BigNumberish,
    amount: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  createEvent(
    uri: string,
    startDate: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  createMarketTicket(
    eventId: BigNumberish,
    tokenId: BigNumberish,
    nftContract: string,
    purchaseLimit: BigNumberish,
    totalSupply: BigNumberish,
    price: BigNumberish,
    royaltyFee: BigNumberish,
    maxResalePrice: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getAllEvents(
    overrides?: CallOverrides
  ): Promise<TicketMarket.MarketEventStructOutput[]>;

  getEvent(
    _eventId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<TicketMarket.MarketEventStructOutput>;

  getEventTickets(
    _eventId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<TicketMarket.MarketTicketStructOutput[]>;

  getMyEvents(
    overrides?: CallOverrides
  ): Promise<TicketMarket.MarketEventStructOutput[]>;

  getMyResaleListings(
    overrides?: CallOverrides
  ): Promise<TicketMarket.ResaleTicketStructOutput[]>;

  getMyTickets(
    nftContract: string,
    overrides?: CallOverrides
  ): Promise<TicketMarket.MarketTicketStructOutput[]>;

  getResaleTickets(
    _tokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<TicketMarket.ResaleTicketStructOutput[]>;

  listOnResale(
    nftContract: string,
    _tokenId: BigNumberish,
    price: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  onERC1155BatchReceived(
    arg0: string,
    arg1: string,
    arg2: BigNumberish[],
    arg3: BigNumberish[],
    arg4: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  onERC1155Received(
    arg0: string,
    arg1: string,
    arg2: BigNumberish,
    arg3: BigNumberish,
    arg4: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  supportsInterface(
    interfaceId: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  validateTicket(
    nftContract: string,
    userAddress: string,
    tokenId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    addMoreTicketsToMarket(
      nftContract: string,
      tokenId: BigNumberish,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    buyResaleTicket(
      nftContract: string,
      _resaleId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    buyTicket(
      nftContract: string,
      tokenId: BigNumberish,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    createEvent(
      uri: string,
      startDate: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    createMarketTicket(
      eventId: BigNumberish,
      tokenId: BigNumberish,
      nftContract: string,
      purchaseLimit: BigNumberish,
      totalSupply: BigNumberish,
      price: BigNumberish,
      royaltyFee: BigNumberish,
      maxResalePrice: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    getAllEvents(
      overrides?: CallOverrides
    ): Promise<TicketMarket.MarketEventStructOutput[]>;

    getEvent(
      _eventId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<TicketMarket.MarketEventStructOutput>;

    getEventTickets(
      _eventId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<TicketMarket.MarketTicketStructOutput[]>;

    getMyEvents(
      overrides?: CallOverrides
    ): Promise<TicketMarket.MarketEventStructOutput[]>;

    getMyResaleListings(
      overrides?: CallOverrides
    ): Promise<TicketMarket.ResaleTicketStructOutput[]>;

    getMyTickets(
      nftContract: string,
      overrides?: CallOverrides
    ): Promise<TicketMarket.MarketTicketStructOutput[]>;

    getResaleTickets(
      _tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<TicketMarket.ResaleTicketStructOutput[]>;

    listOnResale(
      nftContract: string,
      _tokenId: BigNumberish,
      price: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    onERC1155BatchReceived(
      arg0: string,
      arg1: string,
      arg2: BigNumberish[],
      arg3: BigNumberish[],
      arg4: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    onERC1155Received(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      arg3: BigNumberish,
      arg4: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    validateTicket(
      nftContract: string,
      userAddress: string,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "MarketEventCreated(uint256,string,uint64,uint256,uint256,address)"(
      eventId?: BigNumberish | null,
      uri?: null,
      startDate?: null,
      ticketTotal?: null,
      ticketsSold?: null,
      owner?: null
    ): MarketEventCreatedEventFilter;
    MarketEventCreated(
      eventId?: BigNumberish | null,
      uri?: null,
      startDate?: null,
      ticketTotal?: null,
      ticketsSold?: null,
      owner?: null
    ): MarketEventCreatedEventFilter;

    "MarketTicketCreated(uint256,uint256,uint256,uint256,uint256,uint256,uint256)"(
      tokenId?: BigNumberish | null,
      eventId?: BigNumberish | null,
      price?: null,
      purchaseLimit?: null,
      totalSupply?: null,
      royaltyFee?: null,
      maxResalePrice?: null
    ): MarketTicketCreatedEventFilter;
    MarketTicketCreated(
      tokenId?: BigNumberish | null,
      eventId?: BigNumberish | null,
      price?: null,
      purchaseLimit?: null,
      totalSupply?: null,
      royaltyFee?: null,
      maxResalePrice?: null
    ): MarketTicketCreatedEventFilter;

    "ResaleTicketCreated(uint256,uint256,address,uint256,bool)"(
      resaleId?: BigNumberish | null,
      tokenId?: BigNumberish | null,
      seller?: null,
      resalePrice?: null,
      sold?: null
    ): ResaleTicketCreatedEventFilter;
    ResaleTicketCreated(
      resaleId?: BigNumberish | null,
      tokenId?: BigNumberish | null,
      seller?: null,
      resalePrice?: null,
      sold?: null
    ): ResaleTicketCreatedEventFilter;
  };

  estimateGas: {
    addMoreTicketsToMarket(
      nftContract: string,
      tokenId: BigNumberish,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    buyResaleTicket(
      nftContract: string,
      _resaleId: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    buyTicket(
      nftContract: string,
      tokenId: BigNumberish,
      amount: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    createEvent(
      uri: string,
      startDate: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    createMarketTicket(
      eventId: BigNumberish,
      tokenId: BigNumberish,
      nftContract: string,
      purchaseLimit: BigNumberish,
      totalSupply: BigNumberish,
      price: BigNumberish,
      royaltyFee: BigNumberish,
      maxResalePrice: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getAllEvents(overrides?: CallOverrides): Promise<BigNumber>;

    getEvent(
      _eventId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getEventTickets(
      _eventId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMyEvents(overrides?: CallOverrides): Promise<BigNumber>;

    getMyResaleListings(overrides?: CallOverrides): Promise<BigNumber>;

    getMyTickets(
      nftContract: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getResaleTickets(
      _tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    listOnResale(
      nftContract: string,
      _tokenId: BigNumberish,
      price: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    onERC1155BatchReceived(
      arg0: string,
      arg1: string,
      arg2: BigNumberish[],
      arg3: BigNumberish[],
      arg4: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    onERC1155Received(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      arg3: BigNumberish,
      arg4: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    validateTicket(
      nftContract: string,
      userAddress: string,
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addMoreTicketsToMarket(
      nftContract: string,
      tokenId: BigNumberish,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    buyResaleTicket(
      nftContract: string,
      _resaleId: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    buyTicket(
      nftContract: string,
      tokenId: BigNumberish,
      amount: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    createEvent(
      uri: string,
      startDate: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    createMarketTicket(
      eventId: BigNumberish,
      tokenId: BigNumberish,
      nftContract: string,
      purchaseLimit: BigNumberish,
      totalSupply: BigNumberish,
      price: BigNumberish,
      royaltyFee: BigNumberish,
      maxResalePrice: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getAllEvents(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getEvent(
      _eventId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getEventTickets(
      _eventId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getMyEvents(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getMyResaleListings(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getMyTickets(
      nftContract: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getResaleTickets(
      _tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    listOnResale(
      nftContract: string,
      _tokenId: BigNumberish,
      price: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    onERC1155BatchReceived(
      arg0: string,
      arg1: string,
      arg2: BigNumberish[],
      arg3: BigNumberish[],
      arg4: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    onERC1155Received(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      arg3: BigNumberish,
      arg4: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    validateTicket(
      nftContract: string,
      userAddress: string,
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
